### ISSUE TITLE
질문과 답변 매칭이 이상한 부분이 있어요!

### ISSUE THREAD

**Issue by jacinder** [kapable/kapable.github.io#1]
https://kapable.github.io/kapable.github.io/lovelevel/ 페이지에서 테스트 하다가 질문/답변 매칭이 이상한 부분을 발견했습니다.
TEST.js파일 1050줄 부분입니다

**Comment by kapable** [comment]
발견 후 알려주셔서 감사합니다. 해당 콘텐츠 텍스트 변경 완료했습니다.
