### ISSUE TITLE
wrong href link

### ISSUE THREAD

**Issue by evanxue76** [kapable/kapable.github.io#4]
https://github.com/kapable/kapable.github.io/blob/48e3d98ead92a38e275ea0afb8a9c45b57a3a9f2/src/components/Intro.js#L155

there is double "h" in link

**Comment by jkRaccoon** [comment]
thanks for report bug :) we will fix soon

**Comment by kapable** [comment]
thanks for your checking. we've just fixed it! @PolarPig
